using SunnyRewards.Helios.ETL.Common.Domain.Models;

namespace SunnyRewards.Helios.ETL.Core.Domain.Models
{
    public class ETLMonetaryTransactionModel : BaseModel
    {
        public virtual int MonetaryTransactionId { get; set; }
        public virtual char RecordType { get; set; }
        public virtual decimal IssuerClientId { get; set; }
        public virtual string ClientName { get; set; }
        public virtual decimal SubProgramId { get; set; }
        public virtual string SubProgramName { get; set; }
        public virtual decimal Bin { get; set; }
        public virtual string BinCurrencyAlpha { get; set; }
        public virtual string BinCurrencyCode { get; set; }
        public virtual string BankName { get; set; }
        public virtual string Pan { get; set; }
        public virtual string CardNumber { get; set; }
        public virtual decimal AuthorizationAmount { get; set; }
        public virtual string AuthorizationCode { get; set; }
        public virtual decimal TxnLocalAmount { get; set; }
        public virtual DateTime TxnLocDateTime { get; set; }
        public virtual long TxnSign { get; set; }
        public virtual decimal TransactionCurrencyCode { get; set; }
        public virtual string TransactionCurrencyAlpha { get; set; }
        public virtual decimal TxnTypeCode { get; set; }
        public virtual decimal ReasonCode { get; set; }
        public virtual decimal DerivedRequestCode { get; set; }
        public virtual decimal ResponseCode { get; set; }
        public virtual decimal MatchStatusCode { get; set; }
        public virtual decimal MatchTypeCode { get; set; }
        public virtual DateTime InitialLoadDateFlag { get; set; }
        public virtual decimal Mcc { get; set; }
        public virtual string MerchantCurrencyAlpha { get; set; }
        public virtual string MerchantCurrencyCode { get; set; }
        public virtual string MerchantName { get; set; }
        public virtual string MerchantNumber { get; set; }
        public virtual string ReferenceNumber { get; set; }
        public virtual decimal PaymentMethodId { get; set; }
        public virtual decimal SettleAmount { get; set; }
        public virtual DateTime WcsUtcPostDate { get; set; }
        public virtual decimal SourceCode { get; set; }
        public virtual string AcquirerReferenceNumber { get; set; }
        public virtual decimal? AcquirerId { get; set; }
        public virtual char? AddressVerificationResponse { get; set; }
        public virtual decimal? AdjustAmount { get; set; }
        public virtual string AuthorizationResponse { get; set; }
        public virtual string AvsInformation { get; set; }
        public virtual decimal? Denomination { get; set; }
        public virtual string DirectAccessNumber { get; set; }
        public virtual string CardNumberProxy { get; set; }
        public virtual decimal? FudgeAmt { get; set; }
        public virtual string MatchStatusDescription { get; set; }
        public virtual string MatchTypeDescription { get; set; }
        public virtual string MccDescription { get; set; }
        public virtual string MerchantZip { get; set; }
        public virtual string MerchantCity { get; set; }
        public virtual string MerchantCountryCode { get; set; }
        public virtual string MerchantCountryName { get; set; }
        public virtual string MerchantProvince { get; set; }
        public virtual string MerchantState { get; set; }
        public virtual string MerchantStreet { get; set; }
        public virtual long? Pin { get; set; }
        public virtual string PosData { get; set; }
        public virtual decimal? PosEntryCode { get; set; }
        public virtual string PosEntryDescription { get; set; }
        public virtual decimal? PurseNo { get; set; }
        public virtual string ReasonCodeDescription { get; set; }
        public virtual string DerivedRequestCodeDescription { get; set; }
        public virtual string ResponseDescription { get; set; }
        public virtual string RetrievalRefNo { get; set; }
        public virtual long? Reversed { get; set; }
        public virtual string SourceDescription { get; set; }
        public virtual string TerminalNumber { get; set; }
        public virtual string TxnTypeName { get; set; }
        public virtual string UserId { get; set; }
        public virtual string UserFirstName { get; set; }
        public virtual string UserLastName { get; set; }
        public virtual DateTime? WcsLocalPostDate { get; set; }
        public virtual string Comment { get; set; }
        public virtual string ClientReferenceNumber { get; set; }
        public virtual string ClientSpecificId { get; set; }
        public virtual decimal? ActualRequestCode { get; set; }
        public virtual string ActualRequestCodeDescription { get; set; }
        public virtual string CardholderClientUniqueId { get; set; }
        public virtual string PanProxyNumber { get; set; }
        public virtual string TxnUid { get; set; }
        public virtual string PurseName { get; set; }
        public virtual string PurseStatus { get; set; }
        public virtual DateTime? PurseCreationDate { get; set; }
        public virtual DateTime? PurseEffectiveDate { get; set; }
        public virtual DateTime? PurseExpirationDate { get; set; }
        public virtual DateTime? PurseStatusDate { get; set; }
        public virtual string AssociationSource { get; set; }
        public virtual decimal? ReasonId { get; set; }
        public virtual string ReasonDescription { get; set; }
        public virtual decimal? Variance { get; set; }
        public virtual string ProcessCode { get; set; }
        public virtual string TokenUniqueReferenceId { get; set; }
        public virtual string PanUniqueReferenceId { get; set; }
        public virtual string TokenTransactionId { get; set; }
        public virtual char? TokenStatus { get; set; }
        public virtual string TokenStatusDescription { get; set; }
        public virtual string NetworkReferenceId { get; set; }
        public virtual string MultiClearingIndication { get; set; }
        public virtual decimal? AuthorizationBalance { get; set; }
        public virtual decimal? SettleBalance { get; set; }
        public virtual DateTime? WcsLocalInserted { get; set; }
        public virtual DateTime? WcsUtcInserted { get; set; }
        public virtual DateTime? WcsUtcUpdated { get; set; }
        public virtual decimal? DiscountAmount { get; set; }
        public virtual DateTime? AchEffectiveDate { get; set; }
        public virtual long? CardPresent { get; set; }
        public virtual string DeviceType { get; set; }
        public virtual string SpendCategory { get; set; }
        public virtual string FilterType { get; set; }
        public virtual string PaymentAccountReference { get; set; }
        public virtual string OriginalMerchantNumber { get; set; }
        public virtual DateTime CreateTimestamp { get; set; }
        public virtual long DeleteNbr { get; set; }
        public virtual long BatchFileId { get; set; }
        public virtual int RecordNbr { get; set; }
    }
}
