apiVersion: v1
kind: Service
metadata:
  name: admin-api
  namespace: helios-uat
  labels:
    app: admin-api
spec:
  selector:
    app: admin-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-api-deployment
  namespace: helios-uat
  labels:
    app: admin-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-api
  template:
    metadata:
      labels:
        app: admin-api
    spec:
      serviceAccountName: externalsecretsa
      containers:
      - name: admin-api
        image: 590183943866.dkr.ecr.us-east-2.amazonaws.com/helios-uat-admin-api:IMAGETAG
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "2"
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Uat
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/subnets: 	subnet-01aa62e9e0a455a7c,subnet-0c70e725103bd7937,subnet-044397354d4acd4cf
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: helios-uat-admin-api-lb
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:590183943866:certificate/fa871984-17b4-4901-8038-bfda6439cbcd
    alb.ingress.kubernetes.io/healthcheck-path: /health/live
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
  finalizers:
  - ingress.k8s.aws/resources
  labels:
    app: admin-api
  name: admin-api-ingress
  namespace: helios-uat
spec:
  tls:
    - hosts:
        - admin-api.uat.sunnyrewards.com
      secretName: sunnyrewardsstaruatcert
  ingressClassName: alb
  rules:
  - http:
      paths:
      - backend:
          service:
            name: admin-api
            port:
              number: 80
        path: /*
        pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-01aa62e9e0a455a7c,subnet-0c70e725103bd7937,subnet-044397354d4acd4cf
    alb.ingress.kubernetes.io/security-groups: sg-011850d2f41d2c1a6
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: helios-uat-admin-lb-public
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:590183943866:certificate/fa871984-17b4-4901-8038-bfda6439cbcd
    # Define the path and port for the health check
    alb.ingress.kubernetes.io/healthcheck-path: /health/live
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
  finalizers:
  - ingress.k8s.aws/resources
  labels:
    app: admin-api
  name: admin-api-ingress-public
  namespace: helios-uat
spec:
  tls:
    - hosts:
        - adminp-api.uat.sunnyrewards.com
  ingressClassName: alb
  rules:
  - http:
      paths:
      - backend:
          service:
            name: admin-api
            port:
              number: 80
        path: /*
        pathType: ImplementationSpecific
