apiVersion: v1
kind: Service
metadata:
  name: admin-api
  namespace: helios-qa
  labels:
    app: admin-api
spec:
  selector:
    app: admin-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: admin-api-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: admin-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-api-deployment
  namespace: helios-qa
  labels:
    app: admin-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-api
  template:
    metadata:
      labels:
        app: admin-api
      annotations:
        eks.amazonaws.com/compute-type: ec2
    spec:
      serviceAccountName: externalsecretsa
      containers:
      - name: admin-api
        image: 375611915274.dkr.ecr.us-east-2.amazonaws.com/admin-qa-api:IMAGETAG
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "2"
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Qa
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/subnets: 	subnet-0301cfd9019f3df82,subnet-015750ea274f518c1,subnet-0d5d712d0a331bbf4
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:375611915274:certificate/1887fc9d-c7b8-4371-94c7-77280eec9793
    alb.ingress.kubernetes.io/healthcheck-path: /health/live
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
  finalizers:
  - ingress.k8s.aws/resources
  labels:
    app: admin-api
  name: admin-api-ingress
  namespace: helios-qa
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - backend:
          service:
            name: admin-api
            port:
              number: 80
        path: /*
        pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-0c5f93ef24f0e7910,subnet-0af13bab56879697b,subnet-06b8437e29f865e69
    alb.ingress.kubernetes.io/security-groups: sg-0cf30fba0faaaf2c1
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: helios-qa-admin-lb-public
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:375611915274:certificate/ae9e64dc-083c-4998-8ae6-6e0e16be613f
    # Define the path and port for the health check
    alb.ingress.kubernetes.io/healthcheck-path: /health/live
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
  finalizers:
  - ingress.k8s.aws/resources
  labels:
    app: admin-api
  name: admin-api-ingress-public
  namespace: helios-qa
spec:
  tls:
    - hosts:
        - adminp-api.qa.sunnybenefits.com
  ingressClassName: alb
  rules:
  - http:
      paths:
      - backend:
          service:
            name: admin-api
            port:
              number: 80
        path: /*
        pathType: ImplementationSpecific
