using AutoMapper;
using SunnyRewards.Helios.ETL.Core.Domain.Dtos.FIS;
using SunnyRewards.Helios.ETL.Core.Domain.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SunnyRewards.Helios.ETL.Infrastructure.Profiles
{
    public class MonetaryTransactionMappingProfile : Profile
    {
        public MonetaryTransactionMappingProfile()
        {
            CreateMap<FISMonetoryDetailDto, ETLMonetaryTransactionModel>()
            .ForMember(dest => dest.MonetaryTransactionId, opt => opt.Ignore()) // Assuming this is auto-generated or handled separately
            .ForMember(dest => dest.RecordType, opt => opt.MapFrom(src => src.RecordType))
            .ForMember(dest => dest.IssuerClientId, opt => opt.MapFrom(src => src.IssuerClientID))
            .ForMember(dest => dest.ClientName, opt => opt.MapFrom(src => src.ClientName))
            .ForMember(dest => dest.SubProgramId, opt => opt.MapFrom(src => src.SubProgramID))
            .ForMember(dest => dest.SubProgramName, opt => opt.MapFrom(src => src.SubProgramName))
            .ForMember(dest => dest.Bin, opt => opt.MapFrom(src => src.BIN))
            .ForMember(dest => dest.BinCurrencyAlpha, opt => opt.MapFrom(src => src.BINCurrencyAlpha))
            .ForMember(dest => dest.BinCurrencyCode, opt => opt.MapFrom(src => src.BINCurrencyCode))
            .ForMember(dest => dest.BankName, opt => opt.MapFrom(src => src.BankName))
            .ForMember(dest => dest.Pan, opt => opt.MapFrom(src => src.PAN))
            .ForMember(dest => dest.CardNumber, opt => opt.MapFrom(src => src.CardNumber))
            .ForMember(dest => dest.AuthorizationAmount, opt => opt.MapFrom(src => src.AuthorizationAmount))
            .ForMember(dest => dest.AuthorizationCode, opt => opt.MapFrom(src => src.AuthorizationCode))
            .ForMember(dest => dest.TxnLocalAmount, opt => opt.MapFrom(src => src.TxnLocalAmount))
            .ForMember(dest => dest.TxnLocDateTime, opt => opt.MapFrom(src => src.TxnLocDateTime))
            .ForMember(dest => dest.TxnSign, opt => opt.MapFrom(src => src.TxnSign))
            .ForMember(dest => dest.TransactionCurrencyCode, opt => opt.MapFrom(src => src.TransactionCurrencyCode))
            .ForMember(dest => dest.TransactionCurrencyAlpha, opt => opt.MapFrom(src => src.TransactionCurrencyAlpha))
            .ForMember(dest => dest.TxnTypeCode, opt => opt.MapFrom(src => src.TxnTypeCode))
            .ForMember(dest => dest.ReasonCode, opt => opt.MapFrom(src => src.ReasonCode))
            .ForMember(dest => dest.DerivedRequestCode, opt => opt.MapFrom(src => src.DerivedRequestCode))
            .ForMember(dest => dest.ResponseCode, opt => opt.MapFrom(src => src.ResponseCode))
            .ForMember(dest => dest.MatchStatusCode, opt => opt.MapFrom(src => src.MatchStatusCode))
            .ForMember(dest => dest.MatchTypeCode, opt => opt.MapFrom(src => src.MatchTypeCode))
            .ForMember(dest => dest.InitialLoadDateFlag, opt => opt.MapFrom(src => src.InitialLoadDateFlag))
            .ForMember(dest => dest.Mcc, opt => opt.MapFrom(src => src.MCC))
            .ForMember(dest => dest.MerchantCurrencyAlpha, opt => opt.MapFrom(src => src.MerchantCurrencyAlpha))
            .ForMember(dest => dest.MerchantCurrencyCode, opt => opt.MapFrom(src => src.MerchantCurrencyCode))
            .ForMember(dest => dest.MerchantName, opt => opt.MapFrom(src => src.MerchantName))
            .ForMember(dest => dest.MerchantNumber, opt => opt.MapFrom(src => src.MerchantNumber))
            .ForMember(dest => dest.ReferenceNumber, opt => opt.MapFrom(src => src.ReferenceNumber))
            .ForMember(dest => dest.PaymentMethodId, opt => opt.MapFrom(src => src.PaymentMethodID))
            .ForMember(dest => dest.SettleAmount, opt => opt.MapFrom(src => src.SettleAmount))
            .ForMember(dest => dest.WcsUtcPostDate, opt => opt.MapFrom(src => src.WCSUTCPostDate))
            .ForMember(dest => dest.SourceCode, opt => opt.MapFrom(src => src.SourceCode))
            .ForMember(dest => dest.AcquirerReferenceNumber, opt => opt.MapFrom(src => src.AcquirerReferenceNumber))
            .ForMember(dest => dest.AcquirerId, opt => opt.MapFrom(src => src.AcquirerID))
            .ForMember(dest => dest.AddressVerificationResponse, opt => opt.MapFrom(src => src.AddressVerificationResponse))
            .ForMember(dest => dest.AdjustAmount, opt => opt.MapFrom(src => src.AdjustAmount))
            .ForMember(dest => dest.AuthorizationResponse, opt => opt.MapFrom(src => src.AuthorizationResponse))
            .ForMember(dest => dest.AvsInformation, opt => opt.MapFrom(src => src.AVSInformation))
            .ForMember(dest => dest.Denomination, opt => opt.MapFrom(src => src.Denomination))
            .ForMember(dest => dest.DirectAccessNumber, opt => opt.MapFrom(src => src.DirectAccessNumber))
            .ForMember(dest => dest.CardNumberProxy, opt => opt.MapFrom(src => src.CardNumberProxy))
            .ForMember(dest => dest.FudgeAmt, opt => opt.MapFrom(src => src.FudgeAmt))
            .ForMember(dest => dest.MatchStatusDescription, opt => opt.MapFrom(src => src.MatchStatusDescription))
            .ForMember(dest => dest.MatchTypeDescription, opt => opt.MapFrom(src => src.MatchTypeDescription))
            .ForMember(dest => dest.MccDescription, opt => opt.MapFrom(src => src.MCCDescription))
            .ForMember(dest => dest.MerchantZip, opt => opt.MapFrom(src => src.MerchantZip))
            .ForMember(dest => dest.MerchantCity, opt => opt.MapFrom(src => src.MerchantCity))
            .ForMember(dest => dest.MerchantCountryCode, opt => opt.MapFrom(src => src.MerchantCountryCode))
            .ForMember(dest => dest.MerchantCountryName, opt => opt.MapFrom(src => src.MerchantCountryName))
            .ForMember(dest => dest.MerchantProvince, opt => opt.MapFrom(src => src.MerchantProvince))
            .ForMember(dest => dest.MerchantState, opt => opt.MapFrom(src => src.MerchantState))
            .ForMember(dest => dest.MerchantStreet, opt => opt.MapFrom(src => src.MerchantStreet))
            .ForMember(dest => dest.Pin, opt => opt.MapFrom(src => src.PIN))
            .ForMember(dest => dest.PosData, opt => opt.MapFrom(src => src.POSData))
            .ForMember(dest => dest.PosEntryCode, opt => opt.MapFrom(src => src.POSEntryCode))
            .ForMember(dest => dest.PosEntryDescription, opt => opt.MapFrom(src => src.POSEntryDescription))
            .ForMember(dest => dest.PurseNo, opt => opt.MapFrom(src => src.PurseNo))
            .ForMember(dest => dest.ReasonCodeDescription, opt => opt.MapFrom(src => src.ReasonCodeDescription))
            .ForMember(dest => dest.DerivedRequestCodeDescription, opt => opt.MapFrom(src => src.DerivedRequestCodeDescription))
            .ForMember(dest => dest.ResponseDescription, opt => opt.MapFrom(src => src.ResponseDescription))
            .ForMember(dest => dest.RetrievalRefNo, opt => opt.MapFrom(src => src.Retrievalrefno))
            .ForMember(dest => dest.Reversed, opt => opt.MapFrom(src => src.Reversed))
            .ForMember(dest => dest.SourceDescription, opt => opt.MapFrom(src => src.SourceDescription))
            .ForMember(dest => dest.TerminalNumber, opt => opt.MapFrom(src => src.TerminalNumber))
            .ForMember(dest => dest.TxnTypeName, opt => opt.MapFrom(src => src.TxnTypeName))
            .ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserID))
            .ForMember(dest => dest.UserFirstName, opt => opt.MapFrom(src => src.UserFirstName))
            .ForMember(dest => dest.UserLastName, opt => opt.MapFrom(src => src.UserLastName))
            .ForMember(dest => dest.WcsLocalPostDate, opt => opt.MapFrom(src => src.WCSLocalPostDate))
            .ForMember(dest => dest.Comment, opt => opt.MapFrom(src => src.Comment))
            .ForMember(dest => dest.ClientReferenceNumber, opt => opt.MapFrom(src => src.ClientReferenceNumber))
            .ForMember(dest => dest.ClientSpecificId, opt => opt.MapFrom(src => src.ClientSpecificID))
            .ForMember(dest => dest.ActualRequestCode, opt => opt.MapFrom(src => src.ActualRequestCode))
            .ForMember(dest => dest.ActualRequestCodeDescription, opt => opt.MapFrom(src => src.ActualRequestCodeDescription))
            .ForMember(dest => dest.CardholderClientUniqueId, opt => opt.MapFrom(src => src.CardholderClientUniqueID))
            .ForMember(dest => dest.PanProxyNumber, opt => opt.MapFrom(src => src.PANProxyNumber))
            .ForMember(dest => dest.TxnUid, opt => opt.MapFrom(src => src.TxnUID))
            .ForMember(dest => dest.PurseName, opt => opt.MapFrom(src => src.PurseName))
            .ForMember(dest => dest.PurseStatus, opt => opt.MapFrom(src => src.PurseStatus))
            .ForMember(dest => dest.PurseCreationDate, opt => opt.MapFrom(src => src.PurseCreationDate))
            .ForMember(dest => dest.PurseEffectiveDate, opt => opt.MapFrom(src => src.PurseEffectiveDate))
            .ForMember(dest => dest.PurseExpirationDate, opt => opt.MapFrom(src => src.PurseExpirationDate))
            .ForMember(dest => dest.PurseStatusDate, opt => opt.MapFrom(src => src.PurseStatusDate))
            .ForMember(dest => dest.AssociationSource, opt => opt.MapFrom(src => src.AssociationSource))
            .ForMember(dest => dest.ReasonId, opt => opt.MapFrom(src => src.ReasonID))
            .ForMember(dest => dest.ReasonDescription, opt => opt.MapFrom(src => src.ReasonDescription))
            .ForMember(dest => dest.Variance, opt => opt.MapFrom(src => src.Variance))
            .ForMember(dest => dest.ProcessCode, opt => opt.MapFrom(src => src.ProcessCode))
            .ForMember(dest => dest.TokenUniqueReferenceId, opt => opt.MapFrom(src => src.TokenUniqueReferenceID))
            .ForMember(dest => dest.PanUniqueReferenceId, opt => opt.MapFrom(src => src.PANUniqueReferenceID))
            .ForMember(dest => dest.TokenTransactionId, opt => opt.MapFrom(src => src.TokenTransactionID))
            .ForMember(dest => dest.TokenStatus, opt => opt.MapFrom(src => src.TokenStatus))
            .ForMember(dest => dest.TokenStatusDescription, opt => opt.MapFrom(src => src.TokenStatusDescription))
            .ForMember(dest => dest.NetworkReferenceId, opt => opt.MapFrom(src => src.NetworkReferenceID))
            .ForMember(dest => dest.MultiClearingIndication, opt => opt.MapFrom(src => src.MultiClearingIndication))
            .ForMember(dest => dest.AuthorizationBalance, opt => opt.MapFrom(src => src.AuthorizationBalance))
            .ForMember(dest => dest.SettleBalance, opt => opt.MapFrom(src => src.SettleBalance))
            .ForMember(dest => dest.WcsLocalInserted, opt => opt.MapFrom(src => src.WCSLocalInserted))
            .ForMember(dest => dest.WcsUtcInserted, opt => opt.MapFrom(src => src.WCSUTCInserted))
            .ForMember(dest => dest.WcsUtcUpdated, opt => opt.MapFrom(src => src.WCSUTCUpdated))
            .ForMember(dest => dest.DiscountAmount, opt => opt.MapFrom(src => src.DiscountAmount))
            .ForMember(dest => dest.AchEffectiveDate, opt => opt.MapFrom(src => src.ACHEffectiveDate))
            .ForMember(dest => dest.CardPresent, opt => opt.MapFrom(src => src.CardPresent))
            .ForMember(dest => dest.DeviceType, opt => opt.MapFrom(src => src.DeviceType))
            .ForMember(dest => dest.SpendCategory, opt => opt.MapFrom(src => src.SpendCategory))
            .ForMember(dest => dest.FilterType, opt => opt.MapFrom(src => src.FilterType))
            .ForMember(dest => dest.PaymentAccountReference, opt => opt.MapFrom(src => src.PaymentAccountReference))
            .ForMember(dest => dest.OriginalMerchantNumber, opt => opt.MapFrom(src => src.OriginalMerchantNumber))
            .ForMember(dest => dest.CreateTimestamp, opt => opt.MapFrom(_ => DateTime.Now))
            .ForMember(dest => dest.DeleteNbr, opt => opt.MapFrom(_ => 0));
        }
    }
}
