---
apiVersion: v1
kind: Service
metadata:
  name: tenant-api
  namespace: tenant-api
  labels:
    app: tenant-api
spec:
  selector:
    app: tenant-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tenant-api-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: tenant-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-api-deployment
  namespace: tenant-api
  labels:
    app: tenant-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-api
  template:
    metadata:
      labels:
        app: tenant-api
      annotations:
        eks.amazonaws.com/compute-type: ec2  
    spec:
      serviceAccountName: tenantsa
      nodeSelector:
        workload: helios-dev
      containers:
      - name: tenant-api
        image: 375611915274.dkr.ecr.us-east-2.amazonaws.com/helios-dev-tenant-api:IMAGETAG
        ports:
        - containerPort: 5001
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "2"
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
