
apiVersion: v1
kind: Service
metadata:
  name: task-api
  namespace: helios-integ
  labels:
    app: task-api
spec:
  selector:
    app: task-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: task-api-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: task-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api-deployment
  namespace: helios-integ
  labels:
    app: task-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
      annotations:
        eks.amazonaws.com/compute-type: ec2
    spec:
      serviceAccountName: externalsecretsa
      containers:
      - name: task-api
        image: 590183943866.dkr.ecr.us-east-2.amazonaws.com/helios-integ-task-api:IMAGETAG
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "2"
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Integ
