apiVersion: v1
kind: Service
metadata:
  name: wallet-api
  namespace: helios-uat
  labels:
    app: wallet-api
spec:
  selector:
    app: wallet-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-api-deployment
  namespace: helios-uat
  labels:
    app: wallet-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-api
  template:
    metadata:
      labels:
        app: wallet-api
    spec:
      serviceAccountName: externalsecretsa
      containers:
      - name: wallet-api
        image: 590183943866.dkr.ecr.us-east-2.amazonaws.com/helios-uat-wallet-api:IMAGETAG
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "2"
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Uat
