apiVersion: v1
kind: ServiceAccount
metadata:
  name: wallet-api-sa
  namespace: helios-sbx
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::768763313030:role/helios-sbx-wallet-api-sa-role
---
apiVersion: v1
kind: Service
metadata:
  name: wallet-api
  namespace: helios-sbx
  labels:
    app: wallet-api
spec:
  selector:
    app: wallet-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-api-deployment
  namespace: helios-sbx
  labels:
    app: wallet-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wallet-api
  template:
    metadata:
      labels:
        app: wallet-api
      annotations:
        eks.amazonaws.com/compute-type: ec2
    spec:
      serviceAccountName: wallet-api-sa
      containers:
        - name: wallet-api
          image: 768763313030.dkr.ecr.us-east-2.amazonaws.com/helios-sbx-wallet-api-ecr:IMAGETAG
          ports:
            - containerPort: 5001
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Sbx
