apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: devsecrets
  namespace: wallet-api
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        jwt:
          serviceAccountRef:
            name: walletsa
