
CREATE TABLE IF NOT EXISTS etl.batch_job_report (
    batch_job_report_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    batch_job_report_code CHARACTER(50) NOT NULL ,
    job_type CHARACTER(100) NOT NULL ,
    job_result_json JSONB NULL,
    create_ts timestamp without time zone NOT NULL,
    create_user CHARACTER(255) NOT NULL,
	update_user CHARACTER(255),
	update_ts timestamp without time zone NULL,
    delete_nbr bigint DEFAULT 0 NOT NULL
);

GRANT ALL ON TABLE etl.batch_job_report TO hadminusr;
GRANT DELETE, INSERT, UPDATE, SELECT ON TABLE etl.batch_job_report TO happusr;
GRANT SELECT ON TABLE etl.batch_job_report TO hrousr;