CREATE TABLE IF NOT EXISTS etl.member_import_file (
    member_import_file_id BIGINT not null PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    member_import_code VARCHAR(50) NOT NULL,  -- Contains generated MIC code (mic-<guid_without_hyphens>)
    file_name VARCHAR(255) NOT NULL,           -- Name of the imported file
   create_ts timestamp not null,
	update_ts timestamp,
	create_user varchar(50) not null,
	update_user varchar(50),
	delete_nbr bigint not null
);

-- Index to enforce uniqueness on member_import_code and delete_nbr
CREATE UNIQUE INDEX idx_member_import_code_delete_nbr 
ON etl.member_import_file (member_import_code, delete_nbr);

GRANT ALL ON TABLE etl.member_import_file TO hadminusr;
GRANT DELETE, INSERT, UPDATE, SELECT ON TABLE etl.member_import_file TO happusr;
GRANT SELECT ON TABLE etl.member_import_file TO hrousr;

CREATE TABLE IF NOT EXISTS etl.member_import_file_data (
    member_import_file_data_id BIGINT not null PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
    member_import_file_id BIGINT NOT NULL,      -- Foreign key reference to member_import_file
    record_number INT NOT NULL,                 -- The record number within the import file
    raw_data_json JSONB NOT NULL,               -- Raw data record as JSONB
    create_ts timestamp not null,
	update_ts timestamp,
	create_user varchar(50) not null,
	update_user varchar(50),
	delete_nbr bigint not null,
    constraint fk_member_import_file_id
    FOREIGN KEY (member_import_file_id) REFERENCES etl.member_import_file(member_import_file_id)
);

-- Index for querying based on member_import_file_id and delete_nbr
CREATE INDEX idx_member_import_file_id_delete_nbr 
ON etl.member_import_file_data (member_import_file_id, delete_nbr);

GRANT ALL ON TABLE etl.member_import_file_data TO hadminusr;
GRANT DELETE, INSERT, UPDATE, SELECT ON TABLE etl.member_import_file_data TO happusr;
GRANT SELECT ON TABLE etl.member_import_file_data TO hrousr;