CREATE TABLE IF NOT EXISTS etl.batch_job_detail_report (
    batch_job_detail_report_id bigint not null PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    batch_job_report_id bigint NOT NULL ,
    file_num INTEGER NOT NULL,
    record_num INTEGER NOT NULL,
    record_result_json JSONB NOT NULL,
	create_ts timestamp not null,
	update_ts timestamp,
	create_user varchar(50) not null,
	update_user varchar(50),
	delete_nbr bigint not null,
	constraint fk_batch_job_report_id
	FOREIGN KEY(batch_job_report_id) 
	REFERENCES etl.batch_job_report(batch_job_report_id)
);

GRANT ALL ON TABLE etl.batch_job_detail_report TO hadminusr;
GRANT DELETE, INSERT, UPDATE, SELECT ON TABLE etl.batch_job_detail_report TO happusr;
GRANT SELECT ON TABLE etl.batch_job_detail_report TO hrousr;