CREATE TABLE IF NOT EXISTS etl.batch_operation (
    batch_operation_id bigint not null PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    batch_operation_code varchar(50) NOT NULL ,
    batch_operation_group_code varchar(50) NOT NULL ,
    batch_action varchar(20) ,
    action_description_json JSONB NULL,
	create_ts timestamp not null,
	update_ts timestamp,
	create_user varchar(50) not null,
	update_user varchar(50),
	delete_nbr bigint not null
);

GRANT ALL ON TABLE etl.batch_operation TO hadminusr;
GRANT DELETE, INSERT, UPDATE, SELECT ON TABLE etl.batch_operation TO happusr;
GRANT SELECT ON TABLE etl.batch_operation TO hrousr;