-- create table for event_handler_script
CREATE TABLE IF NOT EXISTS admin.event_handler_script (
  event_handler_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  event_handler_code character varying(50) NOT NULL, 
  tenant_code character varying(50) NOT NULL,
  script_id bigint NOT NULL,
  event_type character varying(80) NOT NULL,
  event_sub_type character varying(80) NOT NULL,
  create_ts timestamp without time zone NOT NULL,
  update_ts timestamp without time zone,
  create_user character varying(50) NOT NULL,
  update_user character varying(50),
  delete_nbr bigint NOT NULL,
  CONSTRAINT event_handler_script_pkey PRIMARY KEY (event_handler_id),
  CONSTRAINT fkey_script_id FOREIGN KEY (script_id)
    REFERENCES admin.script (script_id)
);

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE admin.event_handler_script TO happusr;
GRANT SELECT ON TABLE admin.event_handler_script TO hrousr;
GRANT ALL ON TABLE admin.event_handler_script TO hschupdusr;
GRANT ALL ON TABLE admin.event_handler_script TO hadminusr;

CREATE UNIQUE INDEX IF NOT EXISTS idx_event_handler_code_delete_nbr
ON admin.event_handler_script(event_handler_code, delete_nbr);

CREATE UNIQUE INDEX IF NOT EXISTS idx_tenant_code_event_type_event_subtype_delete_nbr
ON admin.event_handler_script(tenant_code, event_type,event_sub_type, delete_nbr);

-- create table for event_handler_result
CREATE TABLE IF NOT EXISTS admin.event_handler_result (
  event_handler_result_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  event_code character varying(50) NOT NULL,
  event_handler_script_id bigint NOT NULL,
  event_handler_name character varying(80) NOT NULL,
  event_data jsonb NOT NULL,
  result_status character varying(20) NOT NULL,
  result_description_json jsonb NULL,
  create_ts timestamp without time zone NOT NULL,
  update_ts timestamp without time zone,
  create_user character varying(50) NOT NULL,
  update_user character varying(50),
  delete_nbr bigint NOT NULL,
  CONSTRAINT event_handler_result_pkey PRIMARY KEY (event_handler_result_id),
  CONSTRAINT fkey_event_handler_script_id FOREIGN KEY (event_handler_script_id)
    REFERENCES admin.event_handler_script (event_handler_id) 
);

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE admin.event_handler_result TO happusr;
GRANT SELECT ON TABLE admin.event_handler_result TO hrousr;
GRANT ALL ON TABLE admin.event_handler_result TO hschupdusr;
GRANT ALL ON TABLE admin.event_handler_result TO hadminusr;