-- 1. Create the 'script' table

CREATE TABLE IF NOT EXISTS admin.script (
    script_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
    script_code VARCHAR(50) NOT NULL,  
    script_name VARCHAR(80) NOT NULL,
    script_description VARCHAR(1024),
    script_json JSONB NOT NULL,
	script_source VARCHAR,
    create_ts timestamp not null,
	update_ts timestamp,
	create_user varchar(50) not null,
	update_user varchar(50),
	delete_nbr bigint not null
);

-- Unique index on script_code + delete_nbr
CREATE UNIQUE INDEX IF NOT EXISTS idx_script_code_delete_nbr 
ON admin.script (script_code, delete_nbr);

-- Unique index on script_name + delete_nbr
CREATE UNIQUE INDEX IF NOT EXISTS idx_script_name_delete_nbr 
ON admin.script (script_name, delete_nbr);

GRANT ALL ON TABLE admin.script TO hadminusr;
GRANT DELETE, INSERT, UPDATE, SELECT ON TABLE admin.script TO happusr;
GRANT SELECT ON TABLE admin.script TO hrousr;

-- 2. Create the 'tenant_task_reward_script' table
CREATE TABLE IF NOT EXISTS admin.tenant_task_reward_script (
    tenant_task_reward_script_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    tenant_task_reward_script_code VARCHAR(50) NOT NULL, 
    tenant_code VARCHAR(50) NOT NULL,
    task_reward_code VARCHAR(50) NOT NULL,
    script_type VARCHAR(50) NOT NULL,   
    script_id BIGINT NOT NULL,
    create_ts timestamp not null,
	update_ts timestamp,
	create_user varchar(50) not null,
	update_user varchar(50),
	delete_nbr bigint not null,
    CONSTRAINT fk_script_id FOREIGN KEY (script_id) REFERENCES admin.script (script_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_task_reward_code_script_type_delete_nbr 
ON admin.tenant_task_reward_script (task_reward_code, script_type, delete_nbr);

GRANT ALL ON TABLE admin.tenant_task_reward_script TO hadminusr;
GRANT DELETE, INSERT, UPDATE, SELECT ON TABLE admin.tenant_task_reward_script TO happusr;
GRANT SELECT ON TABLE admin.tenant_task_reward_script TO hrousr;

-- 3. Create the 'task_reward_script_result' table
CREATE TABLE IF NOT EXISTS admin.task_reward_script_result (
    task_reward_script_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    tenant_task_reward_script_id BIGINT NOT NULL,
    consumer_code VARCHAR(50) NOT NULL,
    execution_context_json JSONB,
    execution_result_json JSONB,
	create_ts timestamp not null,
	update_ts timestamp,
	create_user varchar(50) not null,
	update_user varchar(50),
	delete_nbr bigint not null,
    CONSTRAINT fk_tenant_task_reward_script FOREIGN KEY (tenant_task_reward_script_id) REFERENCES admin.tenant_task_reward_script (tenant_task_reward_script_id)
);

GRANT ALL ON TABLE admin.task_reward_script_result TO hadminusr;
GRANT DELETE, INSERT, UPDATE, SELECT ON TABLE admin.task_reward_script_result TO happusr;
GRANT SELECT ON TABLE admin.task_reward_script_result TO hrousr;