CREATE SCHEMA IF NOT EXISTS admin;

CREATE TABLE IF NOT EXISTS admin.audit_trail
(
    audit_trail_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
    source_module varchar(80) not null,
    source_context varchar(255) not null,
    audit_name varchar(80) not null,
    audit_message varchar(1024) not null,
    create_ts timestamp not null,
    create_user varchar(50) not null,
    delete_nbr bigint NOT NULL,
    audit_data varchar,
    audit_json_data jsonb
);

ALTER SCHEMA admin OWNER TO hadminusr;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA admin TO happusr;
GRANT SELECT ON ALL TABLES IN SCHEMA admin TO hrousr;

GRANT USAGE ON SCHEMA admin TO happusr, hrousr;