-- 1. Create phone_type table if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT FROM information_schema.tables 
        WHERE table_schema = 'huser' AND table_name = 'phone_type'
    ) THEN
        CREATE TABLE huser.phone_type (
            phone_type_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
            phone_type_code VARCHAR(50) UNIQUE NOT NULL,
            phone_type_name TEXT NOT NULL UNIQUE,
            description TEXT,
            create_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            update_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            create_user VARCHAR(50),
            update_user VARCHAR(50),
            delete_nbr BIGINT DEFAULT 0
        );
    END IF;
END
$$;

GRANT ALL ON TABLE huser.phone_type TO hadminusr;
GRANT DELETE, INSERT, UPDATE, SELECT ON TABLE huser.phone_type TO happusr;
GRANT SELECT ON TABLE huser.phone_type TO hrousr;

-- 2. Create phone_number table if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT FROM information_schema.tables 
        WHERE table_schema = 'huser' AND table_name = 'phone_number'
    ) THEN
        CREATE TABLE huser.phone_number (
            phone_number_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
            phone_type_id BIGINT NOT NULL REFERENCES huser.phone_type(phone_type_id),
            phone_number_code VARCHAR(50) UNIQUE NOT NULL,
            person_id BIGINT NOT NULL REFERENCES huser.person(person_id) ON DELETE CASCADE,
            phone_number VARCHAR NOT NULL,
            is_primary BOOLEAN DEFAULT FALSE,
            is_verified BOOLEAN DEFAULT FALSE,
            verified_at TIMESTAMP,
			source TEXT,
            create_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            update_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            create_user VARCHAR(50),
            update_user VARCHAR(50),
            delete_nbr BIGINT DEFAULT 0
        );
    END IF;
END
$$;
 
GRANT ALL ON TABLE huser.phone_number TO hadminusr;
GRANT DELETE, INSERT, UPDATE, SELECT ON TABLE huser.phone_number TO happusr;
GRANT SELECT ON TABLE huser.phone_number TO hrousr;

-- Create supporting indexes
CREATE UNIQUE INDEX IF NOT EXISTS one_primary_phone_number_per_person
    ON huser.phone_number(person_id)
    WHERE is_primary = TRUE;

CREATE INDEX IF NOT EXISTS idx_phone_number_person_id
    ON huser.phone_number(person_id);

CREATE INDEX IF NOT EXISTS idx_phone_number_person_primary
    ON huser.phone_number(person_id, is_primary);

-- 3. Insert 'home' and 'mobile' into phone_type if not already present
INSERT INTO huser.phone_type (
    phone_type_code,
    phone_type_name,
    description,
    create_ts,
    update_ts,
    create_user,
    update_user,
    delete_nbr
)
VALUES 
(
    'ptc-' || REPLACE(gen_random_uuid()::text, '-', ''),
    'HOME',
    'Home phone number',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    'SYSTEM',
    'SYSTEM',
    0
),
(
    'ptc-' || REPLACE(gen_random_uuid()::text, '-', ''),
    'MOBILE',
    'Mobile phone number',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    'SYSTEM',
    'SYSTEM',
    0
);

-- Add  constraint to check primary mobile number condition in huser.phone_number
DO $$
BEGIN
    -- Check if the constraint 'chk_is_primary_phone_type' does not already exist
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.table_constraints 
        WHERE table_schema = 'huser'
          AND table_name = 'phone_number'
          AND constraint_name = 'chk_is_primary_phone_type'
    ) THEN
        -- Add the constraint to enforce the primary phone number conditions
        ALTER TABLE huser.phone_number
        ADD CONSTRAINT chk_is_primary_phone_type
        CHECK (
            (phone_type_id = 2) OR  -- Allows both TRUE and FALSE for is_primary when phone_type_id = 2
            (phone_type_id != 2 AND is_primary = FALSE)  -- Enforces is_primary = FALSE for other types
        );
    END IF;
END $$;

-- Insert primary mobile phone if available and not already present
INSERT INTO huser.phone_number (
    phone_number_code,
    person_id,
    phone_number,
    phone_type_id,
    is_primary,
    is_verified,
    source,
    create_user,
    update_user,
    create_ts,
    update_ts,
    delete_nbr
)
SELECT 
    'pnc-' || replace(gen_random_uuid()::text, '-', ''),
    p.person_id,
    p.phone_number,
    2, -- Mobile
    TRUE,
    FALSE,
    'ETL',
    'ETL',
    'ETL',
    NOW(),
    NOW(),
    0
FROM huser.person p
WHERE p.phone_number IS NOT NULL
  AND p.delete_nbr = 0
  AND NOT EXISTS (
      SELECT 1
      FROM huser.phone_number pn
      WHERE pn.person_id = p.person_id
        AND pn.phone_type_id = 2
        AND pn.delete_nbr = 0
  );

-- Insert home phone only if it's available and not already present
INSERT INTO huser.phone_number (
    phone_number_code,
    person_id,
    phone_number,
    phone_type_id,
    is_primary,
    is_verified,
    source,
    create_user,
    update_user,
    create_ts,
    update_ts,
    delete_nbr
)
SELECT 
    'pnc-' || replace(gen_random_uuid()::text, '-', ''),
    p.person_id,
    p.home_phone_number,
    1, -- Home
    FALSE,
    FALSE,
    'ETL',
    'ETL',
    'ETL',
    NOW(),
    NOW(),
    0
FROM huser.person p
WHERE p.home_phone_number IS NOT NULL
  AND p.delete_nbr = 0
  AND NOT EXISTS (
      SELECT 1
      FROM huser.phone_number pn
      WHERE pn.person_id = p.person_id
        AND pn.phone_type_id = 1
        AND pn.delete_nbr = 0
  );