-- Create table: address_type
CREATE TABLE IF NOT EXISTS huser.address_type (
    address_type_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    address_type_code VARCHAR(50) UNIQUE NOT NULL,
    address_type_name TEXT NOT NULL,
    description TEXT,
    create_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    create_user VARCHAR(50),
    update_user VARCHAR(50),
    delete_nbr BIGINT DEFAULT 0 
);

-- Create table: huser.person_address
CREATE TABLE IF NOT EXISTS huser.person_address (
    person_address_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    address_type_id BIGINT NOT NULL REFERENCES huser.address_type(address_type_id),
    person_id BIGINT NOT NULL REFERENCES huser.person(person_id) ON DELETE CASCADE,
    address_label TEXT,
    line1 VARCHAR(255) NOT NULL,
    line2 VARCHAR(80),
    city VARCHAR(80),
    state VARCHAR(80) NOT NULL,
    postal_code VARCHAR(20),
    region VARCHAR(40),
	country_code VARCHAR(10) NOT NULL,
    country VARCHAR(40),
    source TEXT,
    is_primary BOOLEAN DEFAULT FALSE,
    create_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    create_user VARCHAR(50),
    update_user VARCHAR(50),
    delete_nbr BIGINT DEFAULT 0
);

-- Create supporting indexes
CREATE UNIQUE INDEX IF NOT EXISTS one_primary_address_per_person
    ON huser.person_address(person_id)
    WHERE is_primary = TRUE;

CREATE INDEX IF NOT EXISTS idx_address_person_id
    ON huser.person_address(person_id);

CREATE INDEX IF NOT EXISTS idx_address_person_primary
    ON huser.person_address(person_id, is_primary);

-- Insert address_type_name 'MAILING' into address_type table
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM huser.address_type
        WHERE LOWER(address_type_name) = 'mailing'
          AND delete_nbr = 0
    ) THEN
        INSERT INTO huser.address_type (
            address_type_id,
            address_type_code,
            address_type_name,
            description,
            create_ts,
            update_ts,
            create_user,
            update_user,
            delete_nbr
        )
        VALUES (
            1,
            'atc-' || gen_random_uuid(),
            'MAILING',
            'Mailing address',
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP,
            'system',
            'system',
            0
        );
    END IF;
END $$;