-- Create the table
CREATE TABLE IF NOT EXISTS huser.consumer_history (
   consumer_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    consumer_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    tenant_code VARCHAR(50) NOT NULL,
    consumer_code VARCHAR(50) NOT NULL,
    registration_ts timestamp without time zone,
    eligible_start_ts timestamp without time zone,
    eligible_end_ts timestamp without time zone,
    create_ts timestamp without time zone NOT NULL,
    update_ts timestamp without time zone,
    create_user VARCHAR(50) not null,
    update_user VARCHAR(50),
    delete_nbr INTEGER,
    registered BOOLEAN DEFAULT false,
    eligible BOOLEAN DEFAULT false,
    mem_nbr VARCHAR(100) NOT NULL,
    consumer_attr JSONB,
    subscriber_mem_nbr VARCHAR(100),
    anonymous_code VARCHAR(50) NOT NULL,
    enrollment_status VARCHAR(50) NOT NULL,
    enrollment_status_source VARCHAR(50) ,
    onboarding_state VARCHAR(50) NOT NULL,
    agreement_status VARCHAR(80) NOT NULL,
    region_code VARCHAR(80),
    subscriber_mem_nbr_prefix VARCHAR(80),
    mem_nbr_prefix VARCHAR(80),
    plan_id VARCHAR(80),
    subgroup_id VARCHAR(80),
    plan_type VARCHAR(80),
    agreement_file_name VARCHAR(255),
    is_sso_user BOOLEAN,
    auth0_user_name VARCHAR(255),
    member_id VARCHAR(255),
    member_type VARCHAR(255) not null
);

GRANT ALL ON TABLE huser.consumer_history TO hadminusr;
GRANT DELETE, INSERT, UPDATE, SELECT ON TABLE huser.consumer_history TO happusr;
GRANT SELECT ON TABLE huser.consumer_history TO hrousr;
-- Conditionally create composite index on (consumer_code, tenant_code)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes 
        WHERE schemaname = 'huser'
          AND indexname = 'idx_consumer_history_consumer_tenant'
    ) THEN
     EXECUTE '
            CREATE UNIQUE INDEX idx_consumer_history_consumer_tenant
            ON huser.consumer_history (consumer_history_id, consumer_code,tenant_code, delete_nbr)';
       
    END IF;
END
$$;
----- insert data
DO $$
BEGIN
    -- Check if consumer_history table exists
    IF EXISTS (
        SELECT FROM information_schema.tables 
        WHERE table_schema = 'huser' 
          AND table_name = 'consumer_history'
    ) THEN

        -- Optional: Use a transaction block
        BEGIN
            -- Truncate table
            TRUNCATE TABLE huser.consumer_history;

            -- Insert data from consumer table
            INSERT INTO huser.consumer_history (
                consumer_id,
                person_id,
                tenant_code,
                consumer_code,
                registration_ts,
                eligible_start_ts,
                eligible_end_ts,
                create_ts,
                update_ts,
                create_user,
                update_user,
                delete_nbr,
                registered,
                eligible,
                mem_nbr,
                consumer_attr,
                subscriber_mem_nbr,
                anonymous_code,
                enrollment_status,
                enrollment_status_source,
                onboarding_state,
                agreement_status,
                region_code,
                subscriber_mem_nbr_prefix,
                mem_nbr_prefix,
                plan_id,
                subgroup_id,
                plan_type,
                agreement_file_name,
                is_sso_user,
                auth0_user_name,
                member_id,
                member_type
            )
            SELECT 
                consumer_id,
                person_id,
                tenant_code,
                consumer_code,
                registration_ts,
                eligible_start_ts,
                eligible_end_ts,
                create_ts,
                update_ts,
                create_user,
                update_user,
                delete_nbr,
                registered,
                eligible,
                mem_nbr,
                consumer_attr,
                subscriber_mem_nbr,
                anonymous_code,
                enrollment_status,
                enrollment_status_source,
                onboarding_state,
                agreement_status,
                region_code,
                subscriber_mem_nbr_prefix,
                mem_nbr_prefix,
                plan_id,
                subgroup_id,
                plan_type,
                agreement_file_name,
                is_sso_user,
                auth0_user_name,
                member_id,
                member_type
            FROM huser.consumer;

        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'Error during truncate/insert operation: %', SQLERRM;
            ROLLBACK;
        END;

    ELSE
        RAISE NOTICE 'Table consumer_history does not exist.';
    END IF;
END
$$;


