CREATE TABLE IF NOT EXISTS huser.server_login
(
    server_login_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tenant_code varchar(50) NOT NULL,
    login_ts timestamp without time zone NOT NULL,
    refresh_token_ts timestamp without time zone,
    logout_ts timestamp without time zone,
    api_token character varying(80) COLLATE pg_catalog."default" NOT NULL,
    create_ts timestamp without time zone NOT NULL,
    update_ts timestamp without time zone,
    create_user character varying(50) COLLATE pg_catalog."default" NOT NULL,
    update_user character varying(50) COLLATE pg_catalog."default",
    delete_nbr bigint NOT NULL,
    CONSTRAINT server_login_pkey PRIMARY KEY (server_login_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE huser.server_login TO happusr;
GRANT SELECT ON TABLE huser.server_login TO hrousr;