-- Create the table huser.consumer_activity with the specified columns
CREATE TABLE IF NOT EXISTS huser.consumer_activity (
  consumer_activity_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
  consumer_activity_code CHARACTER VARYING(50) NOT NULL, -- Unique code for each activity (e.g., cat-<guid>)
  tenant_code CHARACTER VARYING(50) NOT NULL, 
  consumer_code CHARACTER VARYING(50) NOT NULL,
  activity_source CHARACTER VARYING(50) NOT NULL, -- Source of the activity (e.g., BENEFITS_MOBILE_APP)
  activity_type CHARACTER VARYING(50) NOT NULL, -- Type of activity (e.g., PRODUCT_SEARCH)
  activity_detail_json JSONB NOT NULL, -- Details of the activity in JSON format
  create_ts TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
  update_ts TIMESTAMP WITHOUT TIME ZONE, 
  create_user CHARACTER VARYING(50) NOT NULL, 
  update_user CHARACTER VARYING(50), 
  delete_nbr BIGINT NOT NULL, 
  CONSTRAINT consumer_activity_pkey PRIMARY KEY (consumer_activity_id) 
);

-- Create a unique index on consumer_activity_code and delete_nbr 
CREATE UNIQUE INDEX IF NOT EXISTS idx_consumer_activity_code_delete_nbr 
ON huser.consumer_activity(consumer_activity_code, delete_nbr);

-- Create a non-unique index on consumer_code, activity_type, and delete_nbr 
CREATE INDEX IF NOT EXISTS idx_consumer_code_activity_type_delete_nbr 
ON huser.consumer_activity(consumer_code, activity_type, delete_nbr);

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE huser.consumer_activity TO happusr; 
GRANT SELECT ON TABLE huser.consumer_activity TO hrousr; 
GRANT ALL ON TABLE huser.consumer_activity TO hschupdusr; 
GRANT ALL ON TABLE huser.consumer_activity TO hadminusr; 
