create table huser.consumer_login
(
consumer_login_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
consumer_id bigint not null,
login_ts timestamp not null, 
refresh_token_ts timestamp ,
logout_ts timestamp ,
access_token varchar(2048)not null ,
create_ts timestamp not null,
update_ts timestamp ,
create_user varchar(50) not null,
update_user varchar(50),
delete_nbr bigint not null,
constraint fk_consumer_id
FOREIGN KEY(consumer_id) 
REFERENCES huser.consumer(consumer_id)
);