-- Script for new table creation huser.consumer_device

CREATE TABLE IF NOT EXISTS huser.consumer_device (
    consumer_device_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),
    consumer_device_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    tenant_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    consumer_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    device_id_hash character varying(80) COLLATE pg_catalog."default" NOT NULL,
    device_id_enc character varying(1024) COLLATE pg_catalog."default" NOT NULL,
    device_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    device_attr_json jsonb NOT NULL,
    create_ts timestamp without time zone NOT NULL,
    update_ts timestamp without time zone,
    create_user character varying(50) COLLATE pg_catalog."default" NOT NULL,
    update_user character varying(50) COLLATE pg_catalog."default",
    delete_nbr bigint NOT NULL,
    CONSTRAINT consumer_device_pkey PRIMARY KEY (consumer_device_id)
);
 
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE huser.consumer_device TO happusr;

GRANT SELECT ON TABLE huser.consumer_device TO hrousr;

GRANT ALL ON TABLE huser.consumer_device TO hschupdusr;

GRANT ALL ON TABLE huser.consumer_device TO hadminusr;
-- Unique index for consumer_device_code + delete_nbr
CREATE UNIQUE INDEX IF NOT EXISTS idx_consumer_device_0
ON huser.consumer_device USING btree
(consumer_device_code COLLATE pg_catalog."default" ASC NULLS LAST, delete_nbr ASC NULLS LAST)
TABLESPACE pg_default;

-- Unique index for consumer_code + device_id_hash + delete_nbr
CREATE UNIQUE INDEX IF NOT EXISTS idx_consumer_device_1
ON huser.consumer_device USING btree
(consumer_code COLLATE pg_catalog."default" ASC NULLS LAST, device_id_hash COLLATE pg_catalog."default" ASC NULLS LAST, delete_nbr ASC NULLS LAST)
TABLESPACE pg_default;

-- Non-unique index for tenant_code + consumer_code + delete_nbr
CREATE INDEX IF NOT EXISTS idx_consumer_device_2
ON huser.consumer_device USING btree
(tenant_code COLLATE pg_catalog."default" ASC NULLS LAST, consumer_code COLLATE pg_catalog."default" ASC NULLS LAST, delete_nbr ASC NULLS LAST)
TABLESPACE pg_default;
