CREATE SCHEMA IF NOT EXISTS huser;

create table huser.person
(
person_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
person_code varchar(50) unique not null,
first_name varchar(80) not null, 
last_name varchar(80) not null, 
language_code varchar(5) not null,
member_since timestamp not null,
create_ts timestamp not null,
update_ts timestamp,
create_user varchar(50) not null,
update_user varchar(50),
delete_nbr bigint not null
);
CREATE UNIQUE INDEX idx_person_code_delete_nbr ON huser.person(person_code, delete_nbr);

ALTER TABLE huser.person
ADD COLUMN email varchar(100) NOT NULL DEFAULT 'test@xyz.com';

Alter Table huser.person
Add Column city varchar(80),
Add Column country varchar(40),
Add Column year_of_birth int,
Add Column postal_code varchar(20),
Add Column phone_number varchar(20),
Add Column region varchar(40)

create table huser.role
(
role_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
role_code varchar(50) unique not null,
role_name varchar(80) not null,
role_description varchar(1024),
create_ts timestamp not null,
update_ts timestamp,
create_user varchar(50) not  null,
update_user varchar(50),
delete_nbr bigint not null
);
CREATE UNIQUE INDEX idx_role_code_delete_nbr ON huser.role(role_code, delete_nbr);	
CREATE UNIQUE INDEX idx_role_name_delete_nbr ON huser.role(role_name, delete_nbr);
	
	
create table  huser.person_role
(
person_role_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
person_id bigint not null,
role_id  bigint not null,
create_ts timestamp not null,
update_ts timestamp,
create_user varchar(50) not null,
update_user varchar(50),
delete_nbr bigint not null,
constraint fk_person_id
FOREIGN KEY(person_id) 
REFERENCES huser.person(person_id),
constraint fk_role_id
FOREIGN KEY(role_id) 
REFERENCES huser.role(role_id)
);
CREATE UNIQUE INDEX idx_person_id_role_id_delete_nbr ON huser.person_role(person_id, role_id, delete_nbr);


create table huser.consumer
(
consumer_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
person_id bigint not null,
tenant_code varchar(50) not null,
consumer_code varchar(50)unique not null,
registered bit(1) not null default '0',
eligible bit(1) not null default '0',
registration_ts timestamp	,
eligible_start_ts timestamp,
eligible_end_ts timestamp	,
create_ts timestamp not null,
update_ts timestamp,
create_user varchar(50) not null,
update_user varchar(50),
delete_nbr bigint not null,
constraint fk_person_id
FOREIGN KEY(person_id)
REFERENCES huser.person(person_id)
);
CREATE UNIQUE INDEX idx_consumer_code_delete_nbr ON huser.consumer(consumer_code, delete_nbr); 

ALTER TABLE huser.consumer
ADD COLUMN consumer_attr jsonb default '{}'

ALTER TABLE huser.consumer
ALTER COLUMN jsonb SET NOTNULL
