create table wallet.redemption
(
redemption_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
sub_transaction_id bigint not null,
add_transaction_id bigint not null,
revert_sub_transaction_id bigint,
revert_add_transaction_id bigint,
redemption_status varchar(20) not null,
notes varchar(1024),
redemption_ref varchar(80) not null,
redemption_item_description  varchar(1024),
redemption_start_ts timestamp not null,
redemption_complete_ts timestamp,
redemption_revert_ts timestamp,
create_ts timestamp not null,
update_ts timestamp,
create_user varchar(50) not null,
update_user varchar(50),
delete_nbr bigint not null,
constraint fk_sub_transaction_id
FOREIGN KEY(sub_transaction_id) 
REFERENCES wallet.transaction(transaction_id),
constraint fk_add_transaction_id
FOREIGN KEY(add_transaction_id) 
REFERENCES wallet.transaction(transaction_id),
constraint fk_revert_sub_transaction_id
FOREIGN KEY(revert_sub_transaction_id) 
REFERENCES wallet.transaction(transaction_id),
constraint fk_revert_add_transaction_id
FOREIGN KEY(revert_add_transaction_id) 
REFERENCES wallet.transaction(transaction_id)
);

create unique index idx_sub_transaction_id_delete_nbr on wallet.redemption(sub_transaction_id,delete_nbr);
create unique index idx_add_transaction_id_delete_nbr on wallet.redemption(add_transaction_id,delete_nbr);
create unique index idx_redemption_ref_delete_nbr on wallet.redemption(redemption_ref,delete_nbr);