
-- create Table
CREATE TABLE IF NOT EXISTS wallet.wallet_type_transfer_rule (
    wallet_type_transfer_rule_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    wallet_type_transfer_rule_code VARCHAR(50) NOT NULL, -- Unique code for each activity (e.g., wxr-<guid>)
    tenant_code VARCHAR(50) NOT NULL,
    source_wallet_type_id BIGINT NOT NULL,
    target_wallet_type_id BIGINT NOT NULL,
    transfer_rule_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    create_ts TIMESTAMP NOT NULL,
    update_ts TIMESTAMP,
    create_user VARCHAR(50) NOT NULL,
    update_user VARCHAR(50),
    delete_nbr BIGINT NOT NULL,
	 -- Foreign key constraints
	CONSTRAINT fk_source_wallet_type_transfer_rule FOREIGN KEY (source_wallet_type_id) REFERENCES wallet.wallet_type(wallet_type_id),
	CONSTRAINT fk_target_wallet_type_transfer_rule FOREIGN KEY (target_wallet_type_id) REFERENCES wallet.wallet_type(wallet_type_id)
);

-- Unique index on wallet_type_transfer_rule_code and delete_nbr
CREATE UNIQUE INDEX IF NOT EXISTS idx_wallet_type_transfer_rule_code_delete_nbr 
ON wallet.wallet_type_transfer_rule (wallet_type_transfer_rule_code, delete_nbr);

-- Unique index on tenant_code and source_wallet_type_id and delete_nbr
CREATE UNIQUE INDEX IF NOT EXISTS idx_tenant_code_source_wallet_type_id_delete_nbr 
ON wallet.wallet_type_transfer_rule (tenant_code, source_wallet_type_id, delete_nbr);

GRANT ALL ON TABLE wallet.wallet_type_transfer_rule TO hadminusr;
GRANT DELETE, INSERT, UPDATE, SELECT ON TABLE wallet.wallet_type_transfer_rule TO happusr;
GRANT SELECT ON TABLE wallet.wallet_type_transfer_rule TO hrousr;