-- Table: wallet.audit_trail

-- DROP TABLE IF EXISTS wallet.audit_trail;

CREATE TABLE IF NOT EXISTS wallet.audit_trail
(
    audit_trail_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    source_module character varying(80) COLLATE pg_catalog."default" NOT NULL,
    source_context character varying(255) COLLATE pg_catalog."default" NOT NULL,
    audit_name character varying(80) COLLATE pg_catalog."default" NOT NULL,
    audit_message character varying(1024) COLLATE pg_catalog."default" NOT NULL,
    create_ts timestamp without time zone NOT NULL,
    create_user character varying(50) COLLATE pg_catalog."default" NOT NULL,
    delete_nbr bigint NOT NULL,
    audit_data character varying COLLATE pg_catalog."default",
    audit_json_data jsonb,
    CONSTRAINT audit_trail_pkey PRIMARY KEY (audit_trail_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS wallet.audit_trail
    OWNER to hadminusr;

REVOKE ALL ON TABLE wallet.audit_trail FROM happusr;
REVOKE ALL ON TABLE wallet.audit_trail FROM hrousr;

GRANT ALL ON TABLE wallet.audit_trail TO hadminusr;

GRANT DELETE, INSERT, UPDATE, SELECT ON TABLE wallet.audit_trail TO happusr;

GRANT SELECT ON TABLE wallet.audit_trail TO hrousr;