CREATE SCHEMA IF NOT EXISTS wallet;

create table wallet.wallet_type
(
wallet_type_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
wallet_type_code varchar(50) unique not null,
wallet_type_name varchar(80) not null,
create_ts timestamp not null,
update_ts timestamp,
create_user varchar(50) not null,
update_user varchar(50),
delete_nbr bigint not null
);
create unique index idx_wallet_type_code_delete_nbr on wallet.wallet_type(wallet_type_code,delete_nbr);

create table wallet.wallet
(
wallet_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
wallet_type_id bigint not null,	
customer_code varchar(50) not null,
sponsor_code varchar(50),
tenant_code varchar(50),
wallet_code varchar(50) unique not null,
master_wallet bit(1) not null default '0',
wallet_name varchar(80),
active bit(1) not null default '0',
active_start_ts timestamp,
active_end_ts timestamp,
balance decimal not null,
earn_maximum decimal not null,
create_ts timestamp not null,
update_ts timestamp,
create_user varchar(50) not null,
update_user varchar(50),
delete_nbr bigint not null,
constraint fk_wallet_type_id
FOREIGN KEY(wallet_type_id) 
REFERENCES wallet.wallet_type(wallet_type_id)
);
create unique index idx_wallet_code_delete_nbr on wallet.wallet(wallet_code,delete_nbr);
create unique index idx_wallet_code_delete_nbr on wallet.wallet(wallet_code,delete_nbr);

ALTER TABLE wallet.wallet
ADD COLUMN total_earned numeric(14, 2) not null;

ALTER TABLE wallet.wallet
ALTER COLUMN balance TYPE numeric(14, 2);

ALTER TABLE wallet.wallet
ALTER COLUMN earn_maximum  TYPE numeric(14, 2);

create table wallet.consumer_wallet
(
consumer_wallet_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
wallet_id bigint not null,
tenant_code varchar(50) not null,
consumer_code varchar(50) not null,
consumer_role char(1) not null,
earn_maximum decimal not null,
create_ts timestamp not null,
update_ts timestamp,
create_user varchar(50) not null,
update_user varchar(50),
delete_nbr bigint not null,
constraint fk_wallet_id
FOREIGN KEY(wallet_id) 
REFERENCES wallet.wallet(wallet_id)
);
create unique index wallet_id_consumer_code_delete_nbr on wallet.consumer_wallet(wallet_id,consumer_code,delete_nbr);
create unique index wallet_id_consumer_code_delete_nbr on wallet.consumer_wallet(wallet_id,consumer_code,delete_nbr);

ALTER TABLE wallet.consumer_wallet
ALTER COLUMN earn_maximum  TYPE numeric(14, 2);

create table wallet.transaction
(
transaction_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
wallet_id bigint not null,
transaction_code varchar(50) not null,
transaction_type varchar(1) not null,
previous_balance decimal not null,
transaction_amount decimal not null,
balance decimal not null,
prev_wallet_txn_code varchar(100) unique not null,
create_ts timestamp not null,
create_user varchar(50) not null,
delete_nbr bigint not null,
constraint fk_wallet_id
FOREIGN KEY(wallet_id) 
REFERENCES wallet.wallet(wallet_id)
);
create unique index transaction_code_transaction_type_delete_nbr on wallet.transaction(transaction_code,transaction_type,delete_nbr);
create unique index prev_wallet_txn_code_delete_nbr on wallet.transaction(prev_wallet_txn_code,delete_nbr);

ALTER TABLE wallet.transaction
ALTER COLUMN previous_balance TYPE numeric(14, 2);
 
ALTER TABLE wallet.transaction
ALTER COLUMN transaction_amount  TYPE numeric(14, 2) ;
 
ALTER TABLE wallet.transaction
ALTER COLUMN balance TYPE numeric(14, 2);

create table wallet.transaction_detail
(
transaction_detail_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
transaction_id bigint not null,
transaction_detail_type varchar(20) not null,
consumer_code varchar(50),
task_code varchar(50),
notes varchar(1024),
redemption_ref varchar(80),
redemption_item_description varchar(1024),
create_ts timestamp not null,
create_user varchar(50) not null,
delete_nbr bigint not null,
constraint fk_transaction_id
FOREIGN KEY(transaction_id) 
REFERENCES wallet.transaction(transaction_id)
);
create unique index transaction_id_delete_nbr on wallet.transaction_detail(transaction_id,delete_nbr);