
----Create Table task.adventure

CREATE TABLE IF NOT EXISTS task.adventure (
    adventure_id bigint not null PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    adventure_code VARCHAR(50) NOT NULL ,
    adventure_config_json JSONB NOT NULL,
    cms_component_code VARCHAR(50),
    create_ts TIMESTAMP NOT NULL,
    update_ts TIMESTAMP,
    create_user VARCHAR(50) NOT NULL,
    update_user VARCHAR(50),
    delete_nbr BIGINT NOT NULL
);

GRANT ALL ON TABLE task.adventure TO hadminusr;
GRANT DELETE, INSERT, UPDATE, SELECT ON TABLE task.adventure TO happusr;
GRANT SELECT ON TABLE task.adventure TO hrousr;




----Create Table tenant_adventure


CREATE TABLE IF NOT EXISTS task.tenant_adventure (
    tenant_adventure_id bigint not null PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    tenant_adventure_code VARCHAR(50) NOT NULL ,
    tenant_code VARCHAR(50) NOT NULL,
    adventure_id BIGINT NOT NULL REFERENCES task.adventure(adventure_id),
    create_ts TIMESTAMP NOT NULL,
    update_ts TIMESTAMP,
    create_user VARCHAR(50) NOT NULL,
    update_user VARCHAR(50),
    delete_nbr BIGINT NOT NULL
);

GRANT ALL ON TABLE task.tenant_adventure TO hadminusr;
GRANT DELETE, INSERT, UPDATE, SELECT ON TABLE task.tenant_adventure TO happusr;
GRANT SELECT ON TABLE task.tenant_adventure TO hrousr;
