CREATE TABLE task.task_category (
task_category_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
task_category_code varchar(50) NOT NULL,
task_category_name varchar(80) NOT NULL,
task_category_description varchar(255) NULL,
create_ts timestamp NOT NULL,
update_ts timestamp,
create_user varchar(50) NOT NULL,
update_user varchar(50),
delete_nbr bigint NOT NULL);

CREATE UNIQUE INDEX idx_task_category_0
ON task.task_category (task_category_name, delete_nbr);

CREATE TABLE task.tenant_task_category (
tenant_task_category_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
task_category_id bigint NOT NULL,
tenant_code varchar(50) NOT NULL,
resource_json JSONB,
create_ts timestamp NOT NULL,
update_ts timestamp,
create_user varchar(50) NOT NULL,
update_user varchar(50),
delete_nbr bigint NOT NULL,
constraint fk_tenant_task_category_task_category_id
FOREIGN KEY(task_category_id) 
REFERENCES task.task_category(task_category_id));

CREATE UNIQUE INDEX idx_tenant_task_category_0
ON task.tenant_task_category (task_category_id, tenant_code, delete_nbr);

ALTER TABLE task.task
ADD COLUMN task_category_id bigint NULL,
ADD CONSTRAINT fk_task_task_category_id
FOREIGN KEY (task_category_id) 
REFERENCES task.task_category(task_category_id);


INSERT INTO task.task_category(
	task_category_code, task_category_name, task_category_description, create_ts, update_ts, create_user, update_user, delete_nbr)
	VALUES
    ('tcc-' || REPLACE(CAST(gen_random_uuid() as varchar), '-', ''), 'Behavioral Health', 'Behavioral Health', now() at time zone 'utc', null, 'per-915325069cdb42c783dd4601e1d27704', null, 0),
    ('tcc-' || REPLACE(CAST(gen_random_uuid() as varchar), '-', ''), 'Benefits', 'Benefits', now() at time zone 'utc', null, 'per-915325069cdb42c783dd4601e1d27704', null, 0),
    ('tcc-' || REPLACE(CAST(gen_random_uuid() as varchar), '-', ''), 'Clinical Care Gap', 'Clinical Care Gap', now() at time zone 'utc', null, 'per-915325069cdb42c783dd4601e1d27704', null, 0),
    ('tcc-' || REPLACE(CAST(gen_random_uuid() as varchar), '-', ''), 'Company Culture', 'Company Culture', now() at time zone 'utc', null, 'per-915325069cdb42c783dd4601e1d27704', null, 0),
    ('tcc-' || REPLACE(CAST(gen_random_uuid() as varchar), '-', ''), 'Condition Management', 'Condition Management', now() at time zone 'utc', null, 'per-915325069cdb42c783dd4601e1d27704', null, 0),
    ('tcc-' || REPLACE(CAST(gen_random_uuid() as varchar), '-', ''), 'Financial Wellness', 'Financial Wellness', now() at time zone 'utc', null, 'per-915325069cdb42c783dd4601e1d27704', null, 0),
    ('tcc-' || REPLACE(CAST(gen_random_uuid() as varchar), '-', ''), 'Health and Wellness', 'Health and Wellness', now() at time zone 'utc', null, 'per-915325069cdb42c783dd4601e1d27704', null, 0),
    ('tcc-' || REPLACE(CAST(gen_random_uuid() as varchar), '-', ''), 'Pharmacy', 'Pharmacy', now() at time zone 'utc', null, 'per-915325069cdb42c783dd4601e1d27704', null, 0),
    ('tcc-' || REPLACE(CAST(gen_random_uuid() as varchar), '-', ''), 'Preventive Care', 'Preventive Care', now() at time zone 'utc', null, 'per-915325069cdb42c783dd4601e1d27704', null, 0),
    ('tcc-' || REPLACE(CAST(gen_random_uuid() as varchar), '-', ''), 'Virtual Care', 'Virtual Care', now() at time zone 'utc', null, 'per-915325069cdb42c783dd4601e1d27704', null, 0);


update task.task set task_category_id = (select task_category_id from task.task_category where task_category_name='Health and Wellness') where task_name ilike '%download%';
update task.task set task_category_id = (select task_category_id from task.task_category where task_category_name='Condition Management') where task_name ilike '%ease%lower%';
update task.task set task_category_id = (select task_category_id from task.task_category where task_category_name='Clinical Care Gap') where task_name ilike '%complete%osteo%';
update task.task set task_category_id = (select task_category_id from task.task_category where task_category_name='Preventive Care') where task_name ilike '%get%your%pneu%';
update task.task set task_category_id = (select task_category_id from task.task_category where task_category_name='Benefits') where task_name ilike '%thin%abou%star%';
update task.task set task_category_id = (select task_category_id from task.task_category where task_category_name='Financial Wellness') where task_name ilike '%savi%for%col%';
update task.task set task_category_id = (select task_category_id from task.task_category where task_category_name='Behavioral Health') where task_name ilike '%your%mind%matt%';
update task.task set task_category_id = (select task_category_id from task.task_category where task_category_name='Pharmacy') where task_name ilike '%save%mon%pres%';
update task.task set task_category_id = (select task_category_id from task.task_category where task_category_name='Virtual Care') where task_name ilike '%enro%tele%';
update task.task set task_category_id = (select task_category_id from task.task_category where task_category_name='Company Culture') where task_name ilike 'you%earn%it%';


INSERT INTO task.tenant_task_category(
	task_category_id, tenant_code, resource_json, create_ts, update_ts, create_user, update_user, delete_nbr)
	VALUES
		(1, 'ten-ecada21e57154928a2bb959e8365b8b4', '{"taskIconUrl": "/assets/icons/74-head-heart.png"}', now() at time zone 'utc', null, 'per-915325069cdb42c783dd4601e1d27704', null, 0),
		(2, 'ten-ecada21e57154928a2bb959e8365b8b4', '{"taskIconUrl": "/assets/icons/Medical-Note.png"}', now() at time zone 'utc', null, 'per-915325069cdb42c783dd4601e1d27704', null, 0),
		(3, 'ten-ecada21e57154928a2bb959e8365b8b4', '{"taskIconUrl": "/assets/icons/41-user-health-plus.png"}', now() at time zone 'utc', null, 'per-915325069cdb42c783dd4601e1d27704', null, 0),
		(4, 'ten-ecada21e57154928a2bb959e8365b8b4', '{"taskIconUrl": "/assets/icons/Group-1.png"}', now() at time zone 'utc', null, 'per-915325069cdb42c783dd4601e1d27704', null, 0),
		(5, 'ten-ecada21e57154928a2bb959e8365b8b4', '{"taskIconUrl": "/assets/icons/clipboard-list.png"}', now() at time zone 'utc', null, 'per-915325069cdb42c783dd4601e1d27704', null, 0),
		(6, 'ten-ecada21e57154928a2bb959e8365b8b4', '{"taskIconUrl": "/assets/icons/dollar-sign.png"}', now() at time zone 'utc', null, 'per-915325069cdb42c783dd4601e1d27704', null, 0),
		(7, 'ten-ecada21e57154928a2bb959e8365b8b4', '{"taskIconUrl": "/assets/icons/23-stethoscope.png"}', now() at time zone 'utc', null, 'per-915325069cdb42c783dd4601e1d27704', null, 0),
		(8, 'ten-ecada21e57154928a2bb959e8365b8b4', '{"taskIconUrl": "/assets/icons/Pill.png"}', now() at time zone 'utc', null, 'per-915325069cdb42c783dd4601e1d27704', null, 0),
		(9, 'ten-ecada21e57154928a2bb959e8365b8b4', '{"taskIconUrl": "/assets/icons/Calendar-Waiting.png"}', now() at time zone 'utc', null, 'per-915325069cdb42c783dd4601e1d27704', null, 0),
		(10, 'ten-ecada21e57154928a2bb959e8365b8b4', '{"taskIconUrl": "/assets/icons/34-browser-user.png"}', now() at time zone 'utc', null, 'per-915325069cdb42c783dd4601e1d27704', null, 0);
