CREATE SCHEMA IF NOT EXISTS task;

create table task.trivia_question
(
trivia_question_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
trivia_question_code varchar(50) not null,
trivia_json jsonb  not null,
create_ts timestamp not null,
update_ts timestamp,
create_user varchar(50) not null,
update_user varchar(50),
delete_nbr  bigint not null,
question_external_code varchar(80) not null
);

create unique index idx_trivia_question_0
on task.trivia_question(question_external_code, delete_nbr);

create table task.trivia
(
trivia_id	bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
trivia_code varchar(50) not null,
task_reward_id bigint not null,
cta_task_external_code varchar(80),
config_json jsonb not null,
create_ts timestamp not null,
update_ts timestamp,
create_user varchar(50) not null,
update_user varchar(50),
delete_nbr  bigint not null,
constraint fk_task_reward_id
FOREIGN KEY(task_reward_id) 
REFERENCES task.task_reward(task_reward_id)
);

create unique index idx_trivia_0
on task.trivia(task_reward_id, delete_nbr);

create table task.trivia_question_group
(
trivia_question_group_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
trivia_id bigint not null,
trivia_question_id bigint not null,
sequence_nbr int not null,
create_ts timestamp not null,
update_ts timestamp,
create_user varchar(50) not null,
update_user varchar(50),
delete_nbr  bigint not null,

constraint fk_trivia_id 
FOREIGN KEY(trivia_id ) 
REFERENCES task.trivia(trivia_id ),

constraint fk_trivia_question_id 
FOREIGN KEY(trivia_question_id) 
REFERENCES task.trivia_question(trivia_question_id)
);

create unique index idx_trivia_question_group_0
on task.trivia_question_group(trivia_id,trivia_question_id,delete_nbr);


GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA task TO happusr;
GRANT SELECT ON ALL TABLES IN SCHEMA task TO hrousr;

INSERT INTO task.task_type(
	task_type_code, task_type_name, task_type_description, create_ts, update_ts, create_user, update_user, delete_nbr)
	VALUES ('tty-5c44328dce5a4b60ab79ab13e9253f27', 'TRIVIA', 'Trivia questions', now() at time zone 'utc', null, 'per-915325069cdb42c783dd4601e1d27704', null, 0);
