-- Check and Add is_collection column if it does not exist
DO $$ 
DECLARE 
    column_exists BOOLEAN;
BEGIN
    -- Check if the column exists
    SELECT EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'task_reward' 
        AND table_schema = 'task' 
        AND column_name = 'is_collection'
    ) INTO column_exists;

    -- Add column if it does not exist
    IF NOT column_exists THEN
        ALTER TABLE task.task_reward 
        ADD COLUMN is_collection BOOLEAN NOT NULL DEFAULT FALSE;
        RAISE NOTICE 'Column is_collection added successfully to task.task_reward.';
    ELSE
        RAISE NOTICE 'Column is_collection already exists in task.task_reward.';
    END IF;
END $$;

-- Check and Create task_reward_collection table if it does not exist
-- Table: task.task_reward_collection
-- DROP TABLE IF EXISTS task.task_reward_collection;

CREATE TABLE IF NOT EXISTS task.task_reward_collection
(
    task_reward_collection_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    parent_task_reward_id bigint NOT NULL,
    child_task_reward_id bigint NOT NULL,
    unique_child_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    config_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    create_ts timestamp without time zone NOT NULL DEFAULT now(),
    update_ts timestamp without time zone,
    create_user character varying(50) COLLATE pg_catalog."default" NOT NULL,
    update_user character varying(50) COLLATE pg_catalog."default",
    delete_nbr bigint NOT NULL DEFAULT 0,
    CONSTRAINT task_reward_collection_pkey PRIMARY KEY (task_reward_collection_id),
    CONSTRAINT fk_child_task_reward FOREIGN KEY (child_task_reward_id)
        REFERENCES task.task_reward (task_reward_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_parent_task_reward FOREIGN KEY (parent_task_reward_id)
        REFERENCES task.task_reward (task_reward_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

-- Index: idx_unique_child_code_delete_nbr

-- DROP INDEX IF EXISTS task.idx_unique_child_code_delete_nbr;

CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_child_code_delete_nbr
    ON task.task_reward_collection USING btree
    (unique_child_code COLLATE pg_catalog."default" ASC NULLS LAST, delete_nbr ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: idx_unique_parent_child_delete_nbr

-- DROP INDEX IF EXISTS task.idx_unique_parent_child_delete_nbr;

CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_parent_child_delete_nbr
    ON task.task_reward_collection USING btree
    (parent_task_reward_id ASC NULLS LAST, child_task_reward_id ASC NULLS LAST, delete_nbr ASC NULLS LAST)
    TABLESPACE pg_default;

REVOKE ALL ON TABLE task.task_reward_collection FROM anewell;
REVOKE ALL ON TABLE task.task_reward_collection FROM group_readonly;
REVOKE ALL ON TABLE task.task_reward_collection FROM group_rw;
REVOKE ALL ON TABLE task.task_reward_collection FROM happusr;
REVOKE ALL ON TABLE task.task_reward_collection FROM hrousr;

GRANT SELECT ON TABLE task.task_reward_collection TO anewell;

GRANT SELECT ON TABLE task.task_reward_collection TO group_readonly;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE task.task_reward_collection TO group_rw;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE task.task_reward_collection TO happusr;

GRANT SELECT ON TABLE task.task_reward_collection TO hrousr;

GRANT ALL ON TABLE task.task_reward_collection TO hschupdusr;

GRANT ALL ON TABLE task.task_reward_collection TO sderinsu;