CREATE TABLE task.task_external_mapping (
    task_external_mapping_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    tenant_code VARCHAR(50) NOT NULL,
    task_third_party_code VARCHAR(255) NOT NULL,
    task_external_code VARCHAR(80) NOT NULL,
    create_ts TIMESTAMP NOT NULL,
    update_ts TIMESTAMP,
    create_user VARCHAR(50) NOT NULL,
    update_user VARCHAR(50),
    delete_nbr INT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX task_external_mapping_0
ON task.task_external_mapping (tenant_code, task_third_party_code, delete_nbr);

GRANT ALL ON TABLE task.task_external_mapping TO hadminusr;
GRANT DELETE, INSERT, UPDATE, SELECT ON TABLE task.task_external_mapping TO happusr;
GRANT SELECT ON TABLE task.task_external_mapping TO hrousr;
