ALTER TABLE task.task_type
ADD column IF NOT EXISTS is_subtask BOOLEAN not null default false;

ALTER TABLE task.task
ADD column IF NOT EXISTS is_subtask BOOLEAN not null default false;

INSERT INTO task.task_type(
	task_type_code, task_type_name, task_type_description, create_ts, update_ts, create_user, update_user, delete_nbr, is_subtask)
	VALUES ('tty-50b7468213864056989ebe41bd9eb158', 'SPINWHEEL_SUBTASK', 'Spinwheel subtask', now() at time zone 'utc', null, 'per-915325069cdb42c783dd4601e1d27704', null, 0, true);


create table task.subtask 
(
subtask_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
parent_task_reward_id bigint not null,
child_task_reward_id bigint not null,
config_json jsonb not null,
create_ts timestamp not null,
update_ts timestamp,
create_user varchar(50) not null,
update_user varchar(50),
delete_nbr bigint not null,

constraint fk_parent_task_reward_id
FOREIGN KEY(parent_task_reward_id)
REFERENCES task.task_reward(task_reward_id),
 
constraint fk_child_task_reward_id
FOREIGN KEY(child_task_reward_id)
REFERENCES task.task_reward(task_reward_id)
 
);

create unique index idx_subtask_0
on task.subtask(parent_task_reward_id, child_task_reward_id, delete_nbr);

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA task TO happusr;
GRANT SELECT ON ALL TABLES IN SCHEMA task TO hrousr;
