CREATE SCHEMA IF NOT EXISTS task;

create table task.task_type
(
task_type_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
task_type_code varchar(50) unique not null,
task_type_name varchar(80) not null,
task_type_description varchar(1024),
create_ts timestamp not null,
update_ts timestamp,
create_user varchar(50) not null,
update_user varchar(50),
delete_nbr bigint not null
);
create unique index idx_task_type_code_delete_nbr on task.task_type(task_type_code,delete_nbr);
create unique index idx_task_type_name_delete_nbr on task.task_type(task_type_name,delete_nbr);

create table task.task
(
task_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
task_type_id bigint not null,	
task_code varchar(50) unique not null,
task_name varchar(80) not null,
self_report BIT(1) not null default '0',
confirm_report BIT(1) not null default '0',	
create_ts timestamp not null,
update_ts timestamp,
create_user varchar(50) not null,
update_user varchar(50),
delete_nbr bigint not null,
constraint fk_task_type_id
FOREIGN KEY(task_type_id) 
REFERENCES task.task_type(task_type_id)
);
create unique index idx_task_code_delete_nbr on task.task(task_code,delete_nbr);

create table task.reward_type
(
reward_type_id bigint  not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
reward_type_name varchar(80) not null,
reward_type_description varchar(1024) not null,
create_ts timestamp not null,
update_ts timestamp,
create_user varchar(50) not null,
update_user varchar(50),
delete_nbr bigint not null
);
create unique index idx_reward_type_name_delete_nbr on task.reward_type(reward_type_name,delete_nbr);

create table task.task_reward
(
task_reward_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 	
task_id bigint not null,
reward_type_id bigint not null,
tenant_code varchar(50) not null,
task_reward_code varchar(50) unique not null,
reward varchar(1024) not null,
min_task_duration int,
max_task_duration int,
expiry timestamp,
priority int not null,	
create_ts timestamp not null,
update_ts timestamp,
create_user varchar(50) not null,
update_user varchar(50),
delete_nbr bigint not null,	
constraint fk_task_id
FOREIGN KEY(task_id) 
REFERENCES task.task(task_id),
constraint fk_reward_type_id
FOREIGN KEY(reward_type_id) 
REFERENCES task.reward_type(reward_type_id)
);
create unique index idx_task_reward_code_delete_nbr on task.task_reward(task_reward_code,delete_nbr);

create table task.consumer_task
(
consumer_task_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
task_id bigint not null,
tenant_code varchar(50) not null,
consumer_code varchar(50) not null,
task_status varchar(20) not null,
progress int not null,
notes varchar(1024) not null,
task_start_ts timestamp,
task_completed_ts timestamp,
create_ts timestamp not null,
update_ts timestamp,
create_user varchar(50) not null,
update_user varchar(50),
delete_nbr bigint not null,
constraint fk_task_id
FOREIGN KEY(task_id) 
REFERENCES task.task(task_id)
);
create unique index idx_task_id_consumer_code_delete_nbr on task.consumer_task(task_id,consumer_code,delete_nbr);

create table task.terms_of_service 
(
terms_of_service_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
terms_of_service_text varchar not null,
language_code varchar(5) not null,
create_ts timestamp not null,	
update_ts timestamp,
create_user varchar(50) not null,
update_user varchar(50),
delete_nbr bigint not null
);

create table task.task_detail
(
task_detail_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
task_id bigint not null,
language_code varchar(5) not null,
task_header varchar(255) not null,
task_description varchar not null,
terms_of_service_id bigint not null,
create_ts timestamp not null,
update_ts timestamp,
create_user varchar(50) not null,
update_user varchar(50),
delete_nbr bigint not null,
constraint fk_task_id
FOREIGN KEY(task_id) 
REFERENCES task.task(task_id),
constraint fk_terms_of_service_id 
FOREIGN KEY(terms_of_service_id ) 
REFERENCES task.terms_of_service(terms_of_service_id)
);
create unique index task_id_language_code_delete_nbr  on task.task_detail(task_id,language_code,delete_nbr);

ALTER TABLE task.task_detail
ADD COLUMN task_cta_button_text varchar(80) not null default 'Enroll now';