CREATE SCHEMA IF NOT EXISTS tenant;

create table tenant.customer
(
customer_id bigint not null primary key, 
customer_code varchar(50) unique not null,
customer_name varchar(80) not null, 
customer_description varchar(1024) not null,
create_ts timestamp not null,
update_ts timestamp ,
create_user varchar(50) not null,
update_user varchar(50),
delete_nbr bigint not null
);
create unique index idx_customer_code_delete_nbr on tenant.customer(customer_code,delete_nbr);
create unique index idx_customer_name_delete_nbr on tenant.customer(customer_name,delete_nbr);  
 
create table tenant.sponsor
(
sponsor_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
customer_id bigint not null,
sponsor_code varchar(50) unique not null, 
sponsor_name varchar(80) not null,
sponsor_description varchar(1024) not null,
create_ts timestamp not null,
update_ts timestamp ,
create_user varchar(50) not null,
update_user varchar(50),
delete_nbr bigint not null,
constraint fk_customer_id
FOREIGN KEY(customer_id) 
REFERENCES tenant.customer(customer_id)
);
create unique index idx_sponsor_code_delete_nbr on tenant.sponsor(sponsor_code,delete_nbr);
 
create table tenant.tenant
(
tenant_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
sponsor_id bigint not null,
tenant_code varchar(50) unique not null, 
plan_year int not null,
period_start_ts timestamp not null,
period_end_ts timestamp not null,
create_ts timestamp not null,
update_ts timestamp ,
create_user varchar(50) not null,
update_user varchar(50),
delete_nbr bigint not null,
constraint fk_sponsor_id
FOREIGN KEY(sponsor_id) 
REFERENCES tenant.sponsor(sponsor_id)
);
create unique index idx_tenant_code_delete_nbr on tenant.tenant(tenant_code,delete_nbr);
